namespace Accelerator.Commercetools.Importer;

public static class Constants
{
    public static class AutoGeneratedNames
    {   
        public static class FolderName
        {
            public const string Price = "Price_";
            public const string Inventory = "Inventory_";
            public const string Category = "Category_";
            public const string Product = "Product_";
        }

        public const string EndOfAutoGeneratedTypeName = "Generated";
    }
}